This job can be monitored from: https://job.c3se.chalmers.se/alvis/4846137
Filename (participants file):  /mimer/NOBACKUP/groups/brainage/thesis_brainage/folds/CN_controlgroup.csv
Error in naming of file.
We are looking at error data.
Model saved at /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/LILAC_plus_CI/model.pt will be applied to participants at /mimer/NOBACKUP/groups/brainage/thesis_brainage/folds/CN_controlgroup.csv.
Last block has number of input channels: 64
Last block has number of output channels: 16
The model is LILAC_plus.
Loaded 65 image pairs.
Loaded 65 rows of metadata.
Loaded 65 targets.
/mimer/NOBACKUP/groups/brainage/thesis_brainage/my_venv/lib/python3.12/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
error Loss (MSE): 2.5220
error MAE: 1.0467
Saved results to CSV to: /mimer/NOBACKUP/groups/brainage/thesis_brainage/folds/predictions_error.csv.
usage: apply_LILAC.py [-h] [--json JSON]
                      [--participants_file PARTICIPANTS_FILE]
                      [--model_state MODEL_STATE] [--model MODEL]
apply_LILAC.py: error: argument --participants_file: expected one argument
