This job can be monitored from: https://job.c3se.chalmers.se/alvis/4588000
Filename (results):  /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/CS_model/test_fold.csv
We are looking at test data.
Model saved at /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/CS_model/best_model.pt will be applied to participants at /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/CS_model/test_fold.csv.
Last block has number of input channels: 64
Last block has number of output channels: 16
Loaded 100 images.
Loaded 100 rows of metadata.
Loaded 100 targets.
/mimer/NOBACKUP/groups/brainage/thesis_brainage/my_venv/lib/python3.12/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
Traceback (most recent call last):
  File "/mimer/NOBACKUP/groups/brainage/thesis_brainage/scripts/apply_CS_model.py", line 160, in <module>
    results = apply_model(opt, model, participants_df, name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mimer/NOBACKUP/groups/brainage/thesis_brainage/scripts/apply_CS_model.py", line 98, in apply_model
    output = model(x1, x2, meta)
             ^^^^^^^^^^^^^^^^^^^
  File "/mimer/NOBACKUP/groups/brainage/thesis_brainage/my_venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mimer/NOBACKUP/groups/brainage/thesis_brainage/my_venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CS_CNN3D.forward() takes from 2 to 3 positional arguments but 4 were given
