This job can be monitored from: https://job.c3se.chalmers.se/alvis/4898433
Filename (participants file):  /mimer/NOBACKUP/groups/brainage/thesis_brainage/CI_CN_groups/CI_participants.csv
We are looking at CI data.
Model saved at /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/LILAC_CI/model.pt will be applied to participants at /mimer/NOBACKUP/groups/brainage/thesis_brainage/CI_CN_groups/CI_participants.csv.
Last block has number of input channels: 64
Last block has number of output channels: 16
The model is (classic) LILAC.
Loaded 68 image pairs.
Loaded 68 rows of metadata.
Loaded 68 targets.
/mimer/NOBACKUP/groups/brainage/thesis_brainage/my_venv/lib/python3.12/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
CI Loss (MSE): 1.4856
CI MAE: 0.9931
Saved results to CSV to: /mimer/NOBACKUP/groups/brainage/thesis_brainage/CI_CN_groups/predictions_CI.csv.
Saved results to CSV to: /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/LILAC_CI/predictions_CI.csv.
Filename (participants file):  /mimer/NOBACKUP/groups/brainage/thesis_brainage/CI_CN_groups/CN_controlgroup.csv
We are looking at CN data.
Model saved at /mimer/NOBACKUP/groups/brainage/thesis_brainage/results/LILAC_CI/model.pt will be applied to participants at /mimer/NOBACKUP/groups/brainage/thesis_brainage/CI_CN_groups/CN_controlgroup.csv.
Traceback (most recent call last):
  File "/mimer/NOBACKUP/groups/brainage/thesis_brainage/scripts/apply_LILAC.py", line 154, in <module>
    participants_df = pd.read_csv(args.participants_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/Arch/software/SciPy-bundle/2024.05-gfbf-2024a/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/Arch/software/SciPy-bundle/2024.05-gfbf-2024a/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/Arch/software/SciPy-bundle/2024.05-gfbf-2024a/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/Arch/software/SciPy-bundle/2024.05-gfbf-2024a/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/apps/Arch/software/SciPy-bundle/2024.05-gfbf-2024a/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mimer/NOBACKUP/groups/brainage/thesis_brainage/CI_CN_groups/CN_controlgroup.csv'
